version: '3.5'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: clicker
    volumes:
      - pgdbdata:/var/lib/postgresql/data/

volumes:
  pgdbdata: null